language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    - travis@grumpymetalguy.com
sudo: false
cache: cargo
before_script:
  - rustc --version
  - cargo --version
script:
  - cargo test
branches:
  only:
    - master
